language: ruby
rvm:
- 2.3.3
branches:
  only:
    - "/1.(.*)/"
    - master
script: bundle exec jekyll build && npm test
after_script:
#  - cat backstop_data/ci_report/xunit.xml
#  - cat backstop_data/html_report/config.js
before_install:
#  - nvm install node
#  - nvm install v7
#  - nvm use v7
#  - npm install
#  - npm install -g backstopjs
#  - npm install -g http-server
before_script:
  # - git checkout $DEPLOYED_HASH
  - bundle exec jekyll build
#  - npm run reference
  # - git checkout $TRAVIS_PULL_REQUEST_BRANCH
  # - git checkout $TRAVIS_BRANCH
deploy:
  provider: s3
  access_key_id: AKIAJPSOMJEQB55SGEUA
  secret_access_key:
    secure: c8O3I0S6g9Bhg5elxoxEvb3Ew05brJajifgy0ORcQcFDnOBwS7axqHxlpgTHd1Res5ryp1m/0Mk/XSmwSR66QNIgHVBJ+6XxGc+/9xG8TokRVgwDe1Lk0TQgw2TDK9XQ1CO6iV/vsLtepeSuD9t9hD4tq3/LTa+dCsOxwd//4iU=
  bucket: www.frobiovox.com
  region: us-west-1
  local-dir: _site
  skip_cleanup: true
  acl: public_read
  on:
    repo: frob/frob.github.com
env:
  global:
    - DEPLOYED_HASH=d31acaea68a0e6ec13197cfb06f96e8928069f3b
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
