name = "Frobiovox"
license = "MIT"
licenselink = "https://gitlab.com/frob/frobiovox-theme/blob/main/LICENSE"
description = "A Hugo theme"
descriptions = ["one", "two"]
homepage = "https://gitlab.com/frob/frobiovox-theme"
tags = ["blog", "responsive", "minimal"]
features = ["responsive", "clean design"]
min_version = "0.120.0"

[author]
  name = "Frank Anderson"
  homepage = "www.frankrobertanderson.com"
